openapi: 3.0.2
info:
  version: 0.4.0
  title: example-service
servers:
  - url: 'http://localhost:8080/example'
paths:
  /hibernation-pod/{podId}/hello:
    get:
      description: Hello
      parameters:
        - name: podId
          in: path
          description: Identity of a hibernation pod
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
      tags:
        - hibernation-pod
components:
  schemas:
    Hello:
      type: object
      properties:
        message:
          type: string
          example: 'Hello World'
      x-tags:
        - hibernation-pod
