version: "3"
services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    ports:
      - 8081:8081
      - 9902:9901
    command: ["-c", "/etc/front-envoy.yaml", "--service-cluster", "front-proxy"]
