name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download OpenAPI Generator
        run: curl -L https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.0.0/openapi-generator-cli-6.0.0.jar -o /tmp/openapi-generator-cli.jar
      - name: Generate application module
        run: java -DsupportingFiles -jar /tmp/openapi-generator-cli.jar batch application.yaml
      - name: Generate controller module
        run: java -jar /tmp/openapi-generator-cli.jar batch controller.yaml
      - name: Generate client module
        run: java -jar /tmp/openapi-generator-cli.jar generate -c client.yaml --git-user-id=edward-mamezou --git-repo-id=use-openapi-generator
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build application module
        run: (cd modules/application; mvn -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/edward-mamezou/use-openapi-generator --batch-mode deploy)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build controller module
        run: (cd modules/controller; mvn -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/edward-mamezou/use-openapi-generator --batch-mode deploy)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@edward-mamezou'
      - run: (cd modules/client; npm install)
      - run: (NPM_CONFIG_USERCONFIG=`pwd`/.npmrc cd modules/client; npm publish)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build example
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: bootBuildImage -x test --imageName=ghcr.io/edward-mamezou/example:v0.6.0
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ghcr.io/edward-mamezou/example:v0.6.0
